### PR TITLE
fix(ui): support other common SQLite file extensions (like .sqlite)

### LINKED ISSUE #36: SQLite driver should support all common SQLite file extensions
Currently the file picker for SQLite engine uses a ["DB File" filename filter](https://github.com/kareemmahlees/tablex/blob/19b357fb9b89366396914bf9791c214d057f956b/apps/core/src/app/connect/_components/sqlite-connection.tsx#L34) that ignores any file extension but ".db". [Wikipedia:SQLite](https://en.wikipedia.org/wiki/SQLite) lists several other common extensions besides ".db": .sqlite, .sqlite3, .db, .db3, .s3db, .sl3. Could all those be accepted by the file picker?

### PR DESCRIPTION
**Pull request by dbarnett**
Fixes #36.

### CODE REVIEW

**Comment by dbarnett** [comment]
Please LMK if I did the changesets thing properly. It created a new file and I didn't find any other .changesets/ file like that but maybe I'm just the use it since you set it up for the repo?

**Review by kareemmahlees — APPROVED** [review]

**Comment by kareemmahlees** [comment]
Good job 🎉 
You only need to create the changeset file, as you have done, and the workflow will handle the rest.

Otherwise, LGTM 🚀

**Comment by kareemmahlees** [comment]
@all-contributors please add @dbarnett for code

**Comment by kareemmahlees** [comment]
Let me explain the workflow in detail:
- you create a PR with the changes you have made
- at the end of your work you create a changeset file by running `pnpm changeset add`, which will create a changeset file with a dummy name under `.changesets/`

   **What are the situations where you don't add an _acutall_ changeset?**
    If you are updating the docs and/or making changes to the website ( at `apps/web` ), we don't manage the versions of the website, but in either case, the changesets bot which I have installed in the repo will always check if there is a changeset file or not.
So to make the bot happy you add an _empty_ changeset file, by running `pnpm changeset add --empty` which will be automatically deleted when the PR is merged.
- when I merge your PR, the changeset action will detect a change in the `.changesets` folder and will automatically create a PR adding the contents of your generated file to the main [Changelog]() file and then delete that generated file.
 
I hope this explains a bit, if you have any other questions LMK.

**Comment by dbarnett** [comment]
> I hope this explains a bit, if you have any other questions LMK.

Excellent, thanks! If it helps, I sent #41 to clarify several of those things in the docs.

**Pull request merged**
